### ISSUE TITLE
setCurrentUser enabled?

### ISSUE THREAD

**Issue by dbinetti** [ember-cli-sentry/ember-cli-sentry#182]
I might be missing something, but is this supposed to send the current user by default?  I see `setCurrentUser` in a test, but nowhere else in the code.  Am I missing something?

THanks

**Comment by Turbo87** [comment]
>  I see `setCurrentUser` in a test

I am not sure what test you are talking about. Can you send a link to that test? I can't seem to find `setCurrentUser` anywhere in the codebase.

are you talking about https://github.com/ember-cli-sentry/ember-cli-sentry/blob/6cfeb7aaa4e7529c105f9095c7ecac5c9f56a800/tests/dummy/app/routes/application.js#L9?

**Comment by dbinetti** [comment]
Forgive me, I was confusing this with another library (BugSnag). 

Closing the issue; however, if there is a way to provide the user information to Sentry through this add-on I would appreciate the pointer.
