### ISSUE TITLE
Ability to call "before-breadcrumb"

### ISSUE THREAD

**Issue by MichalBryxi** [ember-cli-sentry/ember-cli-sentry#184]
In my app all the `ui.click` breadcrumb look like `div.eight.wide.column > a#ember3796.ui.labeled.icon.button.ember-view`, which is not very helpful.

But (for example) I do use a lot of `data-test` helpers, which would have much more meaning for me when going through the sentry trace. They tend to be way more descriptive of the function of that visual component.

There is a possibility to change the breadcrumb on sentry report via [before-breadcrumb](https://docs.sentry.io/error-reporting/configuration/filtering/?platform=javascript#before-breadcrumb) hook. From the docs of `ember-cli-sentry`, I don't think it's easily accessible?

Would it be possible to:

1. Add option to call `before-breadcrumb` hook using `ember-cli-sentry`.
1. Add a documentation to readme on how-to do that?

Thanks

**Comment by Turbo87** [comment]
`beforeBreadcrump` is an API of `@sentry/browser`, but not of `raven-js`, which we are currently using. see https://github.com/ember-cli-sentry/ember-cli-sentry/issues/133 for more information about that.
