### ISSUE TITLE
Ability to set release manually

### ISSUE THREAD

**Issue by MichalBryxi** [ember-cli-sentry/ember-cli-sentry#185]
Currently the code will set either string `release` or `config.APP.version`. I am using https://github.com/dschmidt/ember-cli-deploy-sentry for deployment and this one puts sentry revision info to HTML meta tag:

```
<meta name="sentry:revision" content="(revision)">
```

There is a recommended way how to extract it on Raven init:

```
Raven.config({
    release: document.querySelector("meta[name='sentry:revision']").content
});
```

But since this addon does not allow to dynamically change `Raven.config.release`, it is not easily possible to use this information when using `ember-cli-sentry`.

Would it be possible to expose `release` as a config parameter of `ember-cli-sentry` that could be a function and hence could extract the meta tag?

Thanks.

**Comment by Turbo87** [comment]
from the README of `ember-cli-deploy-sentry`:
> Install ember-cli-sentry but import the raven service from ember-cli-deploy-sentry/services/raven, which will automatically handle setting up the release version for you.
